[package]
name = "cdragon-binviewer"
version = "0.1.0"
authors = ["Benoît Ryder <benoit@ryder.fr>"]
edition = "2021"
workspace = ".."

[dependencies]
cdragon = { path = "../cdragon" }
cdragon-prop = { path = "../cdragon-prop" }
futures = "0.3"
log = "0.4"
yew = "0.19"
wasm-bindgen = "0.2"
web_logger = "0.2"
web-sys = { version = "0.3", features = ["HtmlInputElement", "DomTokenList"] }
regex = "1"
byteorder = "1"
reqwasm = "0.5"
getrandom = { version = "0.2", features = ["js"] }

[features]
default = ["wasm"]
wasm = ["cdragon-prop/wasm"]

