[package]
name = "cdragon-utils"
version = "0.1.0"
authors = ["Benoît Ryder <benoit@ryder.fr>"]
edition = "2021"

[dependencies]
num-traits = "0.2"
nom = "7"
thiserror = "1"
walkdir = "2"
serde = "1"
serde_json = "1"

