[package]
name = "cdragon-binviewer-tools"
version = "0.1.0"
authors = ["Benoît Ryder <benoit@ryder.fr>"]
edition = "2018"

[dependencies]
cdragon-prop = { path = "../cdragon-prop" }
cdragon-utils = { path = "../cdragon-utils" }
walkdir = "2"
clap = "2"
byteorder = "1"

