[package]
name = "cdragon-wad"
version = "0.1.0"
authors = ["Benoît Ryder <benoit@ryder.fr>"]
edition = "2021"

[dependencies]
cdragon-utils = { path = "../cdragon-utils" }
derive-try-from-primitive = "0.1"
nom = "7"
twox-hash = "1.6"
zstd = "0.11"
serde_json = "1"

[features]
wasm = ["zstd/wasm"]

