[package]
name = "cdragon-wad"
version = "0.1.0"
authors = ["Benoît Ryder <benoit@ryder.fr>"]
edition = "2021"

[dependencies]
cdragon-utils = { path = "../cdragon-utils" }
nom = "7"
num_enum = "0.6"
twox-hash = "1.6"
zstd = "0.12"
serde_json = "1"

[features]
wasm = ["zstd/wasm"]

