[package]
name = "cdragon"
version = "0.1.0"
authors = ["Benoît Ryder <benoit@ryder.fr>"]
edition = "2021"

[dependencies]
cdragon-cdn = { path = "../cdragon-cdn" }
cdragon-prop = { path = "../cdragon-prop" }
cdragon-rman = { path = "../cdragon-rman" }
cdragon-utils = { path = "../cdragon-utils" }
cdragon-wad = { path = "../cdragon-wad" }
clap = "3"
num-traits = "0.2"
walkdir = "2"

