[package]
name = "cdragon-cdn"
version = "0.1.0"
authors = ["Benoît Ryder <benoit@ryder.fr>"]
edition = "2018"

[dependencies]
cdragon-utils = { path = "../cdragon-utils" }
cdragon-rman = { path = "../cdragon-rman" }
memmap = "0.7"
reqwest = "0.9"
serde_json = "1.0"
zstd = "0.5"

