[package]
name = "cdragon-cdn"
version = "0.1.0"
authors = ["Benoît Ryder <benoit@ryder.fr>"]
edition = "2018"

[dependencies]
cdragon-utils = { path = "../cdragon-utils" }
cdragon-rman = { path = "../cdragon-rman" }
memmap = "0.7"
pathdiff = "0.1"
reqwest = "0.9"
serde = "1.0"
serde_json = "1.0"
sha1 = { version = "0.6", features = ["std"] }
zstd = "0.5"
